export const currencies = [
  { name: 'Afghan afghani', id: 'AFN' },
  { name: 'European euro', id: 'EUR' },
  { name: 'Albanian lek', id: 'ALL' },
  { name: 'Algerian dinar', id: 'DZD' },
  { name: 'United States dollar', id: 'USD' },
  { name: 'Angolan kwanza', id: 'AOA' },
  { name: 'East Caribbean dollar', id: 'XCD' },
  { name: 'Argentine peso', id: 'ARS' },
  { name: 'Armenian dram', id: 'AMD' },
  { name: 'Aruban florin', id: 'AWG' },
  { name: 'Saint Helena pound', id: 'SHP' },
  { name: 'Australian dollar', id: 'AUD' },
  { name: 'Azerbaijan manat', id: 'AZN' },
  { name: 'Bahamian dollar', id: 'BSD' },
  { name: 'Bahraini dinar', id: 'BHD' },
  { name: 'Bangladeshi taka', id: 'BDT' },
  { name: 'Barbadian dollar', id: 'BBD' },
  { name: 'Belarusian ruble', id: 'BYN' },
  { name: 'Belize dollar', id: 'BZD' },
  { name: 'West African CFA franc', id: 'XOF' },
  { name: 'Bermudian dollar', id: 'BMD' },
  { name: 'Bhutanese ngultrum', id: 'BTN' },
  { name: 'Bolivian boliviano', id: 'BOB' },
  { name: 'Bosnia and Herzegovina', id: 'BAM' },
  { name: 'Botswana pula', id: 'BWP' },
  { name: 'Brazilian real', id: 'BRL' },
  { name: 'Brunei dollar', id: 'BND' },
  { name: 'Bulgarian lev', id: 'BGN' },
  { name: 'Burundi franc', id: 'BIF' },
  { name: 'Cabo Verdean escudo', id: 'CVE' },
  { name: 'Cambodian riel', id: 'KHR' },
  { name: 'Central African CFA franc', id: 'XAF' },
  { name: 'Canadian dollar', id: 'CAD' },
  { name: 'Cayman Islands dollar', id: 'KYD' },
  { name: 'Chilean peso', id: 'CLP' },
  { name: 'Chinese Yuan Renminbi', id: 'CNY' },
  { name: 'Colombian peso', id: 'COP' },
  { name: 'Comorian franc', id: 'KMF' },
  { name: 'Congolese franc', id: 'CDF' },
  { name: 'Costa Rican colon', id: 'CRC' },
  { name: 'Cuban peso', id: 'CUP' },
  { name: 'Netherlands Antillean guilder', id: 'ANG' },
  { name: 'Czech koruna', id: 'CZK' },
  { name: 'Danish krone', id: 'DKK' },
  { name: 'Djiboutian franc', id: 'DJF' },
  { name: 'East Caribbean dollar', id: 'XCD' },
  { name: 'Dominican peso', id: 'DOP' },
  { name: 'Egyptian pound', id: 'EGP' },
  { name: 'Eritrean nakfa', id: 'ERN' },
  { name: 'Estonian euro', id: 'EUR' },
  { name: 'Swazi lilangeni', id: 'SZL' },
  { name: 'Ethiopian birr', id: 'ETB' },
  { name: 'Falkland Islands pound', id: 'FKP' },
  { name: 'Fijian dollar', id: 'FJD' },
  { name: 'Faroese króna', id: 'none' },
  { name: 'French Polynesian franc', id: 'XPF' },
  { name: 'Gambian dalasi', id: 'GMD' },
  { name: 'Georgian lari', id: 'GEL' },
  { name: 'Ghanaian cedi', id: 'GHS' },
  { name: 'Gibraltar pound', id: 'GIP' },
  { name: 'Hungarian forint', id: 'HUF' },
  { name: 'Icelandic krona', id: 'ISK' },
  { name: 'Indian rupee', id: 'INR' },
  { name: 'Indonesian rupiah', id: 'IDR' },
  { name: 'Iranian rial', id: 'IRR' },
  { name: 'Iraqi dinar', id: 'IQD' },
  { name: 'Irish euro', id: 'EUR' },
  { name: 'Israeli new shekel', id: 'ILS' },
  { name: 'Italian euro', id: 'EUR' },
  { name: 'Jamaican dollar', id: 'JMD' },
  { name: 'Japanese yen', id: 'JPY' },
  { name: 'Jordanian dinar', id: 'JOD' },
  { name: 'Kazakhstani tenge', id: 'KZT' },
  { name: 'Kenyan shilling', id: 'KES' },
  { name: 'Kiribati dollar', id: 'AUD' },
  { name: 'Kosovo euro', id: 'EUR' },
  { name: 'Kuwaiti dinar', id: 'KWD' },
  { name: 'Kyrgyzstani som', id: 'KGS' },
  { name: 'Lao kip', id: 'LAK' },
  { name: 'Latvian euro', id: 'EUR' },
  { name: 'Lebanese pound', id: 'LBP' },
  { name: 'Lesotho loti', id: 'LSL' },
  { name: 'Liberian dollar', id: 'LRD' },
  { name: 'Libyan dinar', id: 'LYD' },
  { name: 'Swiss franc', id: 'CHF' },
  { name: 'Lithuanian euro', id: 'EUR' },
  { name: 'Luxembourg euro', id: 'EUR' },
  { name: 'Macanese pataca', id: 'MOP' },
  { name: 'Malagasy ariary', id: 'MGA' },
  { name: 'Malawian kwacha', id: 'MWK' },
  { name: 'Malaysian ringgit', id: 'MYR' },
  { name: 'Maldivian rufiyaa', id: 'MVR' },
  { name: 'Malian CFA franc', id: 'XOF' },
  { name: 'Mexican peso', id: 'MXN' },
  { name: 'Moldovan leu', id: 'MDL' },
  { name: 'Mongolian tugrik', id: 'MNT' },
  { name: 'Moroccan dirham', id: 'MAD' },
  { name: 'Mozambican metical', id: 'MZN' },
  { name: 'Myanmar kyat', id: 'MMK' },
  { name: 'Namibian dollar', id: 'NAD' },
  { name: 'Nauruan dollar', id: 'AUD' },
  { name: 'Nepalese rupee', id: 'NPR' },
  { name: 'Nicaraguan córdoba', id: 'NIO' },
  { name: 'Nigerian naira', id: 'NGN' },
  { name: 'New Zealand dollar', id: 'NZD' },
  { name: 'North Korean won', id: 'KPW' },
  { name: 'Norwegian krone', id: 'NOK' },
  { name: 'Omani rial', id: 'OMR' },
  { name: 'Pakistani rupee', id: 'PKR' },
  { name: 'Palauan dollar', id: 'USD' },
  { name: 'Palestinian shekel', id: 'ILS' },
  { name: 'Panamanian balboa', id: 'PAB' },
  { name: 'Papua New Guinean kina', id: 'PGK' },
  { name: 'Paraguayan guarani', id: 'PYG' },
  { name: 'Peruvian sol', id: 'PEN' },
  { name: 'Philippine peso', id: 'PHP' },
  { name: 'Polish zloty', id: 'PLN' },
  { name: 'Portuguese euro', id: 'EUR' },
  { name: 'Qatari riyal', id: 'QAR' },
  { name: 'Romanian leu', id: 'RON' },
  { name: 'Russian ruble', id: 'RUB' },
  { name: 'Rwandan franc', id: 'RWF' },
  { name: 'Samoan tala', id: 'WST' },
  { name: 'San Marinese euro', id: 'EUR' },
  { name: 'Sao Tomean dobra', id: 'STN' },
  { name: 'Saudi riyal', id: 'SAR' },
  { name: 'Serbian dinar', id: 'RSD' },
  { name: 'Seychellois rupee', id: 'SCR' },
  { name: 'Singapore dollar', id: 'SGD' },
  { name: 'Slovak euro', id: 'EUR' },
  { name: 'Slovenian euro', id: 'EUR' },
  { name: 'Somali shilling', id: 'SOS' },
  { name: 'South African rand', id: 'ZAR' },
  { name: 'South Korean won', id: 'KRW' },
  { name: 'South Sudanese pound', id: 'SSP' },
  { name: 'Spanish euro', id: 'EUR' },
  { name: 'Sri Lankan rupee', id: 'LKR' },
  { name: 'Sudanese pound', id: 'SDG' },
  { name: 'Surinamese dollar', id: 'SRD' },
  { name: 'Swedish krona', id: 'SEK' },
  { name: 'Swiss franc', id: 'CHF' },
  { name: 'Syrian pound', id: 'SYP' },
  { name: 'Tajikistani somoni', id: 'TJS' },
  { name: 'Tanzanian shilling', id: 'TZS' },
  { name: 'Thai baht', id: 'THB' },
  { name: 'Tongan paʻanga', id: 'TOP' },
  { name: 'Trinidad and Tobago dollar', id: 'TTD' },
  { name: 'Tunisian dinar', id: 'TND' },
  { name: 'Turkish lira', id: 'TRY' },
  { name: 'Turkmenistani manat', id: 'TMT' },
  { name: 'Tuvaluan dollar', id: 'AUD' },
  { name: 'Ugandan shilling', id: 'UGX' },
  { name: 'Ukrainian hryvnia', id: 'UAH' },
  { name: 'United Arab Emirates dirham', id: 'AED' },
  { name: 'United States dollar', id: 'USD' },
  { name: 'Uruguayan peso', id: 'UYU' },
  { name: 'Uzbekistani som', id: 'UZS' },
  { name: 'Vanuatu vatu', id: 'VUV' },
  { name: 'Venezuelan bolívar', id: 'VES' },
  { name: 'Vietnamese dong', id: 'VND' },
  { name: 'Yemeni rial', id: 'YER' },
  { name: 'Zambian kwacha', id: 'ZMW' },
  { name: 'Zimbabwean dollar', id: 'ZWL' },
];
